### PR TITLE
Video recording on PC enabled.

### PR DESCRIPTION
**Pull request by TimAidley**
A minimal, redistributable version of ffmpeg is included, and the
video option is added to the multicam.

### CODE REVIEW

**Comment by PerlinWarp** [comment]
Can't wait to try it out!

Reminder for me to check if the [GeneratedThirdPartyNotices.txt](https://github.com/icosa-gallery/open-brush/blob/master/Support/ThirdParty/GeneratedThirdPartyNotices.txt) will update to include the ffmpeg license.

**Comment by TimAidley** [comment]
I don't think you need to add it in to the generated third party notices. In fact, I think you shouldn't add it.

The third party notices are for code that is included in Tilt Brush; ffmpeg is bundled with it, and has its notices alongside it. Given that ffmpeg is GPL you can't mix its code with Tilt Brush.

**Comment by mikeskydev** [comment]
I fixed the conflicts locally, and was able to run the video capture through the editor. On built windows Mono versions, attempting to use the video recorder throws a null reference exception:

```
NullReferenceException: Object reference not set to an instance of an object
  at TiltBrush.UsdPathSerializer.get_IsFinished ()
  at TiltBrush.VideoRecorderUtils.get_UsdPathSerializerIsBlocking ()
```

Note that this doesn't occur if `USD_SUPPORTED` is removed from the Scripting Define Symbols in PC Project settings.

**Comment by TimAidley** [comment]
I need to redo this - I'm not used to the Github PR system and hadn't
realized that later commits would get included in the Pull Request.

**Pull request closed without merging**
