### PR TITLE
Use GLTFast as the primary load; fall back to the old code if it fails

### PR DESCRIPTION
**Pull request by andybak**
Use GLTFast as the importer and fall back to the old code if GltfImport.Load() fails. Tested on most of the Kronos GLTF 2.0 samples. Apart from some more obscure examples, they all seem to import fine.

Current known bugs:

1. [x] ~If you save a scene and reload it, gltfs are missing initially. Loading the scene a second time works~
2. [x] ~Importing point clouds seems to be broken~
3. [x] ~API command for importing models isn't working (code was accidentally removed but added it back in and it still fails~
4. [x] ~App freezes sometimes when importing a model via UI~

### CODE REVIEW

**Review by merulaxr — COMMENTED** [review]
Will do a proper review, but are the sample files and the changes to Main.unity needed? similarly, the shader includes, but I could see that being needed more. are those includes copied directly from glTFast or have they been altered somehow?

**Comment by andybak** [comment]
> [are] the changes to Main.unity needed? 

I can answer this bit. Pretty sure those are the same changes you'd see if you save Main.unity on the xr_vr branch. Just Unity being Unity.

**Comment by andybak** [comment]
> but are the sample files [..] needed? similarly, the shader includes, but I could see that being needed more. are those includes copied directly from glTFast or have they been altered somehow?

@omn0mn0m - you're probably better placed to answer this bit. I haven't looked too closely at samples or shader files.

**Comment by omn0mn0m** [comment]
> Will do a proper review, but are the sample files and the changes to Main.unity needed? similarly, the shader includes, but I could see that being needed more. are those includes copied directly from glTFast or have they been altered somehow?

The sample models were just for me testing with glb files. Sorry, forgot to delete them.

This might be my lack of unity knowledge, but I wasn't able to make .shadervariants without copying the .shader files locally. I figured there should be a way to do it, but could not find it.

**Comment by andybak** [comment]
Not sure where you are with the other cleanups but I think point cloud import is now broken. I think that's a blocker as that's an existing, announced feature. 

It seems to get as far as creating the gameobject but then doesn't convert into a prefab (or give an error)

**Comment by mikeage** [comment]
Are the compilation failures legitimate, or a temporary problem on the server side?

**Comment by andybak** [comment]
Sometimes hard to discern which errors are actually causing the failure. I think it's this part:

`An error occurred while resolving packages:
  Project has invalid dependencies:
    org.nuget.google.apis: Package [org.nuget.google.apis@1.57.0] cannot be found
    org.nuget.google.apis.auth: Package [org.nuget.google.apis.auth@1.57.0] cannot be found
    org.nuget.sharpziplib: Package [org.nuget.sharpziplib@1.3.1] cannot be found
`

I am assuming they are spurious because none of that is specific to this branch.

**Comment by mikeage** [comment]
> Sometimes hard to discern which errors are actually causing the failure. I think it's this part:
> 
> `An error occurred while resolving packages: Project has invalid dependencies: org.nuget.google.apis: Package [org.nuget.google.apis@1.57.0] cannot be found org.nuget.google.apis.auth: Package [org.nuget.google.apis.auth@1.57.0] cannot be found org.nuget.sharpziplib: Package [org.nuget.sharpziplib@1.3.1] cannot be found `
> 
> I am assuming they are spurious because none of that is specific to this branch.

I assumed, but I saw that there were changes to the packages file and just wanted to make sure that these weren't dependencies or anything like that. In any case, looks good now!

**Pull request merged**
