### PR TITLE
Video recording

### PR DESCRIPTION
**Pull request by TimAidley**
I found the issue with video recording. The USD plugin wasn't loading properly, which I think is something related to the change from 2018.4 to 2019.4.

This doesn't fix the issue with the USD dll, but does prevent it not working from screwing over Open Brush.

### CODE REVIEW

**Comment by mikeskydev** [comment]
Ran into some issues:
I was able to record a video, but then after drawing some more I went back to the video recorder and tried to record again. Clicking the trigger didn't start the 'recording' UI nor did it shut it off when clicked again. It appears the recording was still running as the output file showed me attempting to switch to the snapshot tool and failing.

https://user-images.githubusercontent.com/9121007/106753372-7eabaa00-6623-11eb-86dd-a9e2bbebaba9.mp4

**Comment by billyquith** [comment]
Suggestion: Have an "optional extras" or "PC" repo containing tools like this, especially as they are platform specific binaries. "video-capture" or "PC tools" as a subrepo of open-brush. Just to keep on top of potential bloat.

Or could the exe be automatically downloaded from somewhere?

**Comment by TimAidley** [comment]
> Ran into some issues:
> I was able to record a video, but then after drawing some more I went back to the video recorder and tried to record again. Clicking the trigger didn't start the 'recording' UI nor did it shut it off when clicked again. It appears the recording was still running as the output file showed me attempting to switch to the snapshot tool and failing.
> 
>  New_Sketch_08.mp4

Okay, I have turned off USD support entirely for now, as I feel it's better to have video recording with offline rendering coming later, than no video support at all.

**Review by mikeskydev — APPROVED** [review]
Yeah I agree, thanks!

**Pull request merged**
