### PR TITLE
Publish debug symbols to Oculus (Quest only) for crash analysis

### PR DESCRIPTION
**Pull request by mikeage**

### CODE REVIEW

**Comment by mikeskydev** [comment]
@mikeage is this PR affected by #210?

**Comment by mikeage** [comment]
I don't see why it should, but it needs testing. Then again, this PR itself needs testing :-)

**Comment by mikeskydev** [comment]
The debug symbols are for arm64, will that apply if we go back to armv7?

**Comment by mikeage** [comment]
oh, good point. The path will be different. Though FWIW, I don't even know if this is the proper way to upload; I can't test until it's merged...

**Comment by mikeage** [comment]
interestingly, without il2cpp, it seems like there's no symbol generation. I have no idea why. Closing this until we revert #210 or something else

**Pull request closed without merging**
