### PR TITLE
Add advanced camera panel

### PR DESCRIPTION
**Pull request by merulaxr**
Adds the advanced camera panel to the advanced tools menu. Options include
- Toggle PostFX
- Toggle Watermark
- Camera FOV Slider
- (Video mode) Smoothing

Also added promo for contribution back to the project.
Todo: need a better icon for the contribution button in Settings. Currently just the OB logo.

Demo video: https://youtu.be/oKChJ8lnhhA

### CODE REVIEW

**Comment by mikeage** [comment]
Should there be some kind of frame around the preview? It wasn't immediately obvious to me, in the video, that it was there... but maybe first-hand it looks a lot clearer

**Comment by mikeage** [comment]
Or was this just because you somehow snapped it on to the panel instead of holding the camera in your other hand?

**Comment by merulaxr** [comment]
The panel is as-supplied in the original TB code, I've just made it accessible! I think we'll do a second pass to add some user-requested features and we can sort the outline bit then?

**Comment by merulaxr** [comment]
The panel is as-supplied in the original TB code, I've just made it accessible! I think we'll do a second pass to add some user-requested features and we can sort the outline bit then?

**Comment by mikeage** [comment]
Works for me!

**Review by mikeage — APPROVED** [review]

**Pull request merged**
