### PR TITLE
Use Depth Submission Mode

### PR DESCRIPTION
**Pull request by bridgewaterrobbie**
Depth Submission can improve warping on some XR headsets

### CODE REVIEW

**Comment by merulaxr** [comment]
Hi, thanks for the PR! I'd seen this setting but wasn't aware what it did, and documentation is sparse. I saw there was previous issues with setting this on Desktop OpenXR, and I notice that Microsoft recommends 16-bit (1) for HoloLens. Do you have any insight as to whether 16 or 24 is better, just for some background knowledge?

**Comment by bridgewaterrobbie** [comment]
I'm not super clear on the difference, other than things similar to Microsoft's statements that there will be less detail available for the depth which can impact the quality of reprojection. From Microsoft's [own docs:](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-overview/setup.md)
"For HoloLens 2, we recommend using 16-bit depth submission in the settings above. For immersive headsets, you can use 24-bit depth submission. "

I would guess their system has some trouble with the larger image, but can't be sure. I can switch this to 16 bit depth if Hololens is a primary target compared to other headsets(Too bad there doesn't seem to be a smart-switch option)

**Comment by bridgewaterrobbie** [comment]
Hrm, I grabbed the artifacts the CI created for the Windows OpenXR, and this one seems to close on start for me unfortunately. I'm not sure how my change could cause that, or if you have some other issue you might already be aware of.

**Comment by merulaxr** [comment]
Thanks for the link from MS, that clears it up a bit! Is it crashing or just hitting a black screen after loading? I know the most recent xr_v2 is a bit unstable so that might explain it, unfortunately can't check right now.

**Comment by merulaxr** [comment]
> I can switch this to 16 bit depth if Hololens is a primary target

We will eventually get to HoloLens but first we need to come up with a sensible hand tracking UX!

**Comment by bridgewaterrobbie** [comment]
It seems to simply exit, no error or crash that I can see. The logo flashes for a short period of time.

**Comment by bridgewaterrobbie** [comment]
Things seem a bit different than I expected. Using 16 bit depth buffers avoids the exit on the runtimes I can test, which is not an exhaustive list. As far as reprojection is concerned, that's better than nothing.

**Review by merulaxr — APPROVED** [review]
LGTM, thanks for contributing and providing us with this knowledge! By the way, I noticed your committer email, and I'd love to talk more about bringing Open Brush to the platform if possible!

**Comment by bridgewaterrobbie** [comment]
@merulaxr ah oops, that was an accident. There isn't a lot I can really say, except that Openbrush would benefit there if the single-controller use case was considered more.

**Comment by merulaxr** [comment]
That's good to know! For accessibility reasons I had considered looking into a one-handed mode which would obviously help here, but can't put a date on it right now. Thanks!

**Pull request merged**
