### PR TITLE
Project Settings changed and movement of trademarked textures

### PR DESCRIPTION
**Pull request by PerlinWarp**
**In First commit:** 

**Starting to use the Open Brush name.** 
* Updating the project settings with a placeholder logo, updated the project name.
* Used OpenBrush naming in App.cs. 

**Removing Trademarks**
I am hoping the trademarks can just be dropped in with replacements and the materials using them will be updated. 
* Moved trademarked icons from Assets/Resources/Icons to Assets/Resources/Icons/Trademarked 
* Moved trademarked textures from Assets/Textures to Assets/Textures/Trademarked

### CODE REVIEW

**Comment by TimAidley** [comment]
Note that we should be able to use some of those trademarks, as long as we adhere to the branding guidelines.

For instance, we would want to keep the Google Drive icon to denote drive access.

**Comment by PerlinWarp** [comment]
**Added Second commit: Rebranding**

* Added new logos and icons made by [SiMonk0](http://www.furjandesign.com/).  
* Replaced the Trademarked logos with the new ones, kept copies just incase. 
* Used the GUI to regenerate the atlas with the new images. 
*  Updated the prefabs to use new icons.  
* Removed .vscode and added it to gitignore. 
* Removed the Google Copyright 
* Added Trello and a Gdoc to the README

**Comment by PerlinWarp** [comment]
**Added Second commit: **

* Added new logos and icons made by [SiMonk0](http://www.furjandesign.com/).  
* Replaced the Trademarked logos with the new ones 
* Used the GUI to regenerate the atlas with the new images. 
 * Removed .vscode and added it to gitignore. 
 * Removed the Google Copyright

**Comment by mikeskydev** [comment]
Thanks!

**Pull request merged**
