### PR TITLE
Integrate 154, 155, 186, 187, 199 into a single PR

### PR DESCRIPTION
**Pull request by andybak**
Insominx: Added "tags" to brushes and filtering based on them: https://github.com/icosa-gallery/open-brush/pull/154

Andybak: Features/http api: https://github.com/icosa-gallery/open-brush/pull/155

Andybak: Features/snapping: https://github.com/icosa-gallery/open-brush/pull/186

Andybak: Features/color jitter: https://github.com/icosa-gallery/open-brush/pull/187

### CODE REVIEW

**Review by mikeskydev — COMMENTED** [review]
Looking good, great features! Some general notes:

image
Would be good to get some icons on these. Perhaps you have added them but they're not atlased yet?

Color jitter sometimes goes to a black brush and doesn't paint anything, though I think this was a bug already.

I'm wondering if the scripts panel icons should just be moved to settings, as there's also external links there to the help resources! (Have we repointed those at our own sites..?)

Also, I haven't checked so I'm not sure if it's just in this build, but for some reason, clicking the camera paths button spawns two camera path panels.

**Comment by andybak** [comment]
> image Would be good to get some icons on these. Perhaps you have added them but they're not atlased yet?

They are actually Text fields. And they seem to appear sometimes and not others. Still trying to figure out why.
 
> Color jitter sometimes goes to a black brush and doesn't paint anything, though I think this was a bug already.

Is this only for some brushes (for example "Light")? I think I've just noticed that each brush seems to enforce a minimum brightness. Try picking Duct Tape, setting it to the blackest black and then switching to "Light" - you'll notice the color picker changes to a slightly lighter color. I'll need to enforce this same min (and maybe max)

> I'm wondering if the scripts panel icons should just be moved to settings, 

Even though Scripts are a bit niche, the settings panel is several clicks deep - plus it doesn't currently have any "open this panel" buttons so it seems a bit weird to add one (which isn't even really a setting - settings change how other things behave, this panel *does* things. It's a tool or command, not a setting).

Did you maybe mean the popup before that? "More Options"? This currently has the button to open the Labs panel on it. 

I dunno "Scripts" being in "Labs" seems to send the right signal to me. "This is experimental labs stuff".... Especially as we promote other things out of Labs.

> as there's also external links there to the help resources! (Have we repointed those at our own sites..?)

What external links do you mean? I can't see any.

> Also, I haven't checked so I'm not sure if it's just in this build, but for some reason, clicking the camera paths button spawns two camera path panels.

Hmmmmm. I'll investigate. It doesn't seem to cause anything other than a minor cosmetic inconvenience so I'd probably suggest this is ok for beta.

**Review by mikeskydev — CHANGES_REQUESTED** [review]
All works great! Just need to add the namespace and licence to some of the files it seems.

**Comment by mikeskydev** [comment]
Following on from discussion, we're closing in favour of #200 plus more features! 🎉

**Pull request closed without merging**
