### PR TITLE
Return to Gamma color workflow, use Vulkan on Android

### PR DESCRIPTION
**Pull request by merulaxr**
We originally switched to a linear rendering workflow with our move to Unity XR, as it was originally a forced requirement in Unity's OpenXR plugin as well as Meta's. However, we lose the blending and colouring modes that define the look and feel of Open Brush, which is the highest priority for us to preserve what artists expect.

This PR reverts the commits that we made to move to linear. As OpenXR doesn't support gamma on OpenGL ES, we have moved android to use Vulkan.

Thanks to our power users in our Discord for helping me debug the color issues!

### CODE REVIEW

**Review by andybak — APPROVED** [review]
lgtm from a code perspective. I would probably suggest a bit of a dig into the SDK code just to make sure there's no context we've overlooked.

**Comment by merulaxr** [comment]
I'll give the app a full sweep on quest to make sure there isn't any odd shaders that would crash this!

> no context we've overlooked.

I had labelled all linear-related commits as I felt there may be pain points there so I could refer/revert back to them, so we should catch everything. At least, I think we should have!

**Comment by merulaxr** [comment]
Hmm, I'm getting crashes on the PR version when I wasn't on my self-built version. I'll debug. 松田浩二 on Discord also experiencing the crash https://discord.com/channels/783806589991780412/1025178592180699216/1025417065403785226

**Comment by merulaxr** [comment]
Some notes:

Quest + Oculus Plugin crashes.
Quest + Unity's OpenXR (with quest loader) runs, but cannot access oculus specific features like passthrough.

Vulkan PC via SteamVR works, using Valve Index.
Vulkan PC via SteamVR with Oculus link crashes.

**Comment by merulaxr** [comment]
As #299 made Meta's support into an immutable package, we can no longer use the hack (that was broken anyways.) It's now also breaking Android OpenXR. I've filed a bug with Meta, ticket number `40946`.

**Comment by merulaxr** [comment]
@andybak @mikeage This is looking good now! Please can you confirm the Quest version works for you?

**Comment by mikeage** [comment]
Sorry, didn't get to this

**Pull request merged**
