### PR TITLE
Ability to modify guide snap distance via guide panel slider.

### PR DESCRIPTION
**Pull request by insominx**
Added the ability to change the guide snap distance using a slider in the guide panel.

Note, this depends on PR #149 in order to minimize merge conflicts as it also makes changes to the guide panel.

### CODE REVIEW

**Comment by mikeskydev** [comment]
Hi, now that #149 has been merged please can you rebase the changes specific to this PR onto main to resolve the conflicts?

**Comment by insominx** [comment]
> Hi, now that #149 has been merged please can you rebase the changes specific to this PR onto main to resolve the conflicts?
✅

**Review by mikeskydev — CHANGES_REQUESTED** [review]
Still have conflicts I'm afraid. Prefab files in unity can be tricky!

**Comment by insominx** [comment]
> Still have conflicts I'm afraid. Prefab files in unity can be tricky!

Was having trouble doing a rebase.  Settled for a basic merge.

**Review by mikeskydev — APPROVED** [review]
LGTM! Thanks for the quick changes, you just made 0.4.0 😄

**Pull request merged**
