### PR TITLE
Create release upon each build and standardize version numbers

### PR DESCRIPTION
**Pull request by mikeage**
Each push to a PR will create builds (as artifacts only) with the
version number of X.Y.Z and a stamp of gABCDEFA, where X.Y is the last
tag in the main repo of the form vX.Y, Z is the number of commits since
then, and ABCDEFA is the git hash of the tip of PR

Each push to main (icosa-gallery only) will create artifacts of the form
X.Y.Z (same meaning as above), as well as an easier to use 'pre-release'
release on the github releases page. It will also tag the commit with
X.Y.Z (no 'v') to make it easier to cross-reference.

Each push of a tag of the format vX.Y to main will create an official release named X.Y.0.

Both of these releases include the same 4 files; Windows + Oculus, regular +
Experimental. The other artifacts (Mac OS X, Linux, Windows Monoscopic)
remain available from the Artifacts page, but are not exposed on the
'releases' link.

All Oculus builds are signed, and the android-specific bundleVersionCode
is now updated automatically (1000000 * X+1000 * Y+Z) (this is also new here).

The builds for PRs and pre-releases use the `-btb-github` option to change the name and package name to include `github`. The builds for formal releases do not; they should be identical to the ones released for 0.2.0 and 0.1.0. 

Creating a new formal release requires two steps:
* Update the following three files, create a PR as usual, and merge it:
```
  Assets/Scenes/Main.unity:  m_VersionNumber: X.Y.0
  ProjectSettings/ProjectSettings.asset:  bundleVersion: X.Y.0
  README.md:## Current Version: `X.Y.0`
```
* Tag the merge commit with `vX.Y` (do not include the `.0`), and push the
  tag to trigger the actual build of `X.Y.0`.

### CODE REVIEW

**Comment by mikeage** [comment]
FYI @andybak

**Comment by mikeage** [comment]
Ignore the commit names, but you can see a sample pre-release at https://github.com/mikeage/open-brush-actions/releases/tag/0.2.12, a sample release at https://github.com/mikeage/open-brush-actions/releases/tag/0.3.0, and their jobs are https://github.com/mikeage/open-brush-actions/runs/2220637479?check_suite_focus=true and https://github.com/mikeage/open-brush-actions/runs/2220920088?check_suite_focus=true respectively

**Comment by mikeage** [comment]
P.S., I know this looks a bit scary, and I won't lie... it is a bit scary, but I think we're getting to something that will last for quite a long time without needing any tweaks and will greatly simplify both beta testing and actual releases by removing a lot of manual steps, so I hope it's worth it :-)

**Comment by mikeage** [comment]
The Oculus build from this PR:
```
$ apkparser -apk ~/Downloads/Android-Oculus/com.Icosa.OpenBrushgithub.apk | jq '.versionName'
"0.2.12-g7430d43"
```

**Comment by mikeage** [comment]
Converting this to a draft for a few minutes; testing one more thing locally first. We should not be using `-btb-github`, I think, if it's a formal build -- those should have the same name and package name as the "official" builds, since I want them to become the official builds!

**Comment by mikeage** [comment]
One more note; to get this to work, I pushed a new tag `v0.2` to the same commit that has `v0.2.0`, to match the (new) convention. If we decide to refactor / reject this, I can delete v0.2

**Comment by mikeage** [comment]
One open issue -- this doesn't (yet) support creating builds for hotfixes / maintenance releases. TBD, but not, I think, on this PR.

**Comment by mikeage** [comment]
The updated format for the zip files for the release can be seen at this release: https://github.com/mikeage/open-brush-actions/releases/tag/0.4.2

**Comment by mikeage** [comment]
Moving to draft while I check the addition of secrets for formal and pre-release (but not PR) builds

**Review by mikeskydev — APPROVED** [review]
LGTM! Impressive stuff

**Pull request merged**
