### PR TITLE
Delete CI.md

### PR DESCRIPTION
**Pull request by mikeage**
Moved to https://github.com/icosa-gallery/open-brush-docs/blob/master/developer-notes/building-open-brush-using-github-ci.md

### CODE REVIEW

**Comment by andybak** [comment]
Yeah. I'm ambivalent. 

On one hand - more people might find docs in two places
On the other - we have to keep them in sync.

I guess we should just make sure the docs are really clearly signposted. Should this wait until we've got the proper domain for the new docs?

**Comment by mikeage** [comment]
I think one link to the gitbook is enough, especially for a document like this which was quite niche. I definitely don't want to duplicate things.

**Comment by andybak** [comment]
> I think one link to the gitbook is enough, especially for a document like this which was quite niche. I definitely don't want to duplicate things.

Yes - but the bit about waiting for the right domain?

**Comment by mikeage** [comment]
merge now?

**Comment by andybak** [comment]
Yeah but we should add a link to docs in the readme at the same time. I'll do a separate PR for that and we can merge them both together.

**Comment by mikeage** [comment]
ok, great. Between that, this, and #169 , maybe we should just do one PR (then again, they're cheap ;-) )

**Pull request merged**
