### PR TITLE
Make featured sketches bundled with the app

### PR DESCRIPTION
**Pull request by TimAidley**
This PR switches the featured sketches from Poly to bundled with the app. It does this by:

- Making `FileSketchSet` optionally read-only, which is achieved by constructing it with a filepath, which it uses instead of the normal sketch path.
- Creating the readonly `FileSketchSet` instead of the curated `PolySketchSet`
- Adding several tilt files into `Resources/DefaultShowcaseSketches`, and copying them to a Showcase folder in the persistent data

Sketches have either been confirmed as CC-BY or I have the artist permission for them.

### CODE REVIEW

**Comment by mikeage** [comment]
I love this idea.

Do we have any thoughts about how many MB we want to dedicate to this?

**Comment by TimAidley** [comment]
I think 100 - 200 MB. I think it would be nice to have two pages of sketches, which IIRC would be 15 sketches. I think most of the sketches we choose shouldn't be too big, as feel like having to wait for ages for them to load isn't a great first experience, and also we want them to run well on all platforms.

Having just said that though, I am just reaching out to Peter Chan to see if we can include his 'The Rescue' sketch.

**Comment by TimAidley** [comment]
I have found a bunch of sketches on Icosa to bundle, but it occurs to me now that I need to include some metadata about Author for each of them, otherwise I'm breaking CC-BY

**Comment by TimAidley** [comment]
Also, I have moved the featured sketches path in to persistent data.

**Comment by TimAidley** [comment]
I have changed it so that sketches in FileSketchSets that have the filename of the form 'sketchname **by** author' get the HumanName and author set accordingly, so that they are presented as:

Sketch Name
Author

in the sketchbook.

**Comment by TimAidley** [comment]
Also, I have added some sketches taken from Icosa. For these sketches, I was able to confirm they were either released as CC-BY, or I got permission from the author to include them.

**Comment by mikeage** [comment]
Right now, our builds are between 130MB and 200MB, depending on the platform. I'm not sure if I like the idea of packaging quite so much supplemental content, although I do agree that giving people samples and references is engaging. 

Is some of this an outcome of integration with Icosa being incomplete? Might we be able to move to network hosted at some point? That'd make me feel a bit better about doubling the size of our installation (but I'm also always open to other opinions)

**Comment by TimAidley** [comment]
It is my assumption that we will move to getting these from the network, but I feel that the app is made much poorer by not having any art you can browse by default, hence this change.

Currently this sketch set add 112MB to the download, however three of them are quite large, and I could reduce that to 59MB if I removed them.

**Comment by TimAidley** [comment]
I have taken out some of the larger ones and replaced them with smaller ones. The sketches now take up 75MB.

**Comment by TimAidley** [comment]
I have now tested it on the Quest as well as PC and it seems to be working fine.

**Pull request merged**
