### PR TITLE
Feature/merge experimental

### PR DESCRIPTION
**Pull request by andybak**
Phases 1 to 3 are complete. https://github.com/icosa-gallery/open-brush/discussions/322

Needs a UI/UX review. I'd say at bare minimum we can merge when we are confident that:

1. Non-experimental mode is unaffected
2. Experimental mode switching is at an "acceptable to experimental standards" level.

### CODE REVIEW

**Comment by andybak** [comment]
The merge of the build JSON was icky. I did what I could by eye but I want the build to complete to see if I broke anything.

**Comment by mikeage** [comment]
Build workflow changes look good. 

There are still a few references to `EXPERIMENTAL_ENABLED`; I assume the GLTF and UnityODS stuff is less critical, but it looks like there's a bit more to do in Assets/Editor/BuildTiltBrush.cs, no?

**Comment by andybak** [comment]
> There are still a few references to `EXPERIMENTAL_ENABLED`; I assume the GLTF and UnityODS stuff is less critical, but it looks like there's a bit more to do in Assets/Editor/BuildTiltBrush.cs, no?

Yep. I missed that. Last two commits hopefully resolve this.

**Comment by mikeage** [comment]
I think you can also get rid of these now:

```
$ git grep forceExperimental
Assets/Editor/BuildTiltBrush.cs:                consultUserConfig: false, forceExperimental: true);
Assets/Scripts/App.cs:        public TiltBrushManifest GetMergedManifest(bool consultUserConfig, bool forceExperimental = false)
Assets/Scripts/App.cs:                    && m_ManifestExperimental != null) || forceExperimental)
```

**Comment by andybak** [comment]
> I think you can also get rid of these now:

I'm not so sure. GetMergedManifest still needs to be called in two modes "ignore config and always return experimental as well" vs "respect the current user config"

Now I type that I realise that sounds suspiciously close to what the consultUserConfig parameter is probably for but I'm struggling to mentally parse all the possible ways this is going to be called and I'm tempted to just leave it alone.

The crux is this conditional:

    if ((consultUserConfig
                    && m_UserConfig.Flags.ShowDangerousBrushes
                    && m_ManifestExperimental != null) || forceExperimental)U'

**Comment by mikeskydev** [comment]
I think it's fine to leave it for now, I'm happy that it's been tidied up elsewhere!

**Comment by mikeage** [comment]
So maybe I'm missing something obvious, but isn't forceExperimental always going to be set, thereby making that conditional always true?

Also, no need for a [CI build] once a PR is open; it gets built automatically!

**Comment by mikeskydev** [comment]
Noting that `git grep` doesn't show all usages of `forceExperimental` as it's a default parameter, so in some cases it doesn't show up. confirmed with intellisense that it's used elsewhere in it's default `false` mode.

**Comment by mikeage** [comment]
I... I just realized something. People who are on the experimental branch on steam won't get this build, or any subsequent ones. We could push the new combined build to both, until 2.0 (following the same logic as we had in PR #291 ), but they would still need to manually enable the feature. 

Should we do a quick subsequent PR with a popup on start that tells people about the new experimental toggle? Announce in Discord? Something else?

**Comment by mikeage** [comment]
Sorry, not 291, but #315

**Pull request merged**
