### PR TITLE
Simple 2D viewing mode when no headset is present

### PR DESCRIPTION
**Pull request by andybak**

### CODE REVIEW

**Comment by andybak** [comment]
Checks actually pass when I retried: https://github.com/icosa-gallery/open-brush/actions/runs/4376865218

**Comment by mikeage** [comment]
https://discord.com/channels/783806589991780412/804251629993197618/1083437289146945536 for some discussion about this PR

**Review by mikeskydev — CHANGES_REQUESTED** [review]
Nice!

I think the purpose of the dropdown on the error screen could be clearer. Perhaps a text line above the dropdown?

On the navigation, I felt it was far too fast. I could see some larger sketches needing that speed, but perhaps it could be modified by the shift key?

Also , the vertical camera adjustment felt back to front to how I would expect moving a camera around.

**Comment by andybak** [comment]
> Also , the vertical camera adjustment felt back to front to how I would expect moving a camera around.

I'm one of those gamers who immediately turns on "Invert Y axis" on every game. Now I can inflict my preference on the world!

Yeah. No. I guess I'll change it. :-(

**Comment by andybak** [comment]
I've improved this to the point where I think it's ready for review.

**Comment by andybak** [comment]
@mikeskydev 
> On the navigation, I felt it was far too fast. I could see some larger sketches needing that speed, but perhaps it could be modified by the shift key?

Just realised - I overlooked this comment and I haven't changed it. I'll update this now.

**Comment by mikeage** [comment]
What is the relationship between this and Monoscopic mode? Can this replace the monoscopic build?

**Comment by andybak** [comment]
> What is the relationship between this and Monoscopic mode? Can this replace the monoscopic build?

This is intentionally separate from monoscopic mode. It might eventually replace it but at the moment it's very different:

a) Much easier to use. WASD+mouse navigation. Monoscopic is kinda weird.
b) No editing or UI - it simply allows you to load a sketch and fly around it.

**Comment by mikeage** [comment]
Ok, so it's a potential replacement, but currently feature limited. That helps. That also explains why when I tried it, many moons ago, on Mac it looked just like Monoscopic. (do we want to try for a view-only mode on Mac, or would that require spending way too much time getting it to build a VR-capable-but-not-really-so-that-it-fails-every-time build?)

**Comment by mikeage** [comment]
I don't think we'll get there, though, because the only Mac build we have is monoscopic. We don't have an OpenXR or SteamVR build for Mac.

**Comment by mikeskydev** [comment]
A mac build could run without including any of the XR plugins, which should trigger the same conditions as not having a headset plugged in

**Review by mikeskydev — APPROVED** [review]

**Pull request merged**
