### PR TITLE
Feature/large mesh support xr

### PR DESCRIPTION
**Pull request by andybak**

### CODE REVIEW

**Comment by andybak** [comment]
The commit history is a bit messy because I reverted something I accidentally committed but the actual change here is just 3 lines:

https://github.com/icosa-gallery/open-brush/pull/279/files

I've done some light testing. Is it worth merging this as it is to increase the likelyhood of it getting tested more broadly?

**Review by merulaxr — COMMENTED** [review]
Let's give it a shot! I think there might be a higher memory bandwidth associated with 32 bit indexing per https://docs.unity3d.com/ScriptReference/Mesh-indexFormat.html, we should probably come up with a stress test or find a creation by one of our users that can push this to the limit.

**Comment by andybak** [comment]
I did consider making this a config file setting (and defaulting it to "off") but maybe we can merge it for now as is.

The paradox is that the users who probably need this for their export workflow are also the users that will feel any performance pinch from it at runtime.

**Review by merulaxr — APPROVED** [review]
No noticeable performance differences between main compared to this branch on a large sketch. LGTM! let's see how it goes.

**Pull request merged**
