### PR TITLE
[Android] Fix root path for user data

### PR DESCRIPTION
**Pull request by ikopytko**
Currently saving in android version is not available because of broken path. This path will fix it.

### CODE REVIEW

**Comment by PerlinWarp** [comment]
Hey Ivan, thanks for this, where did you grab the apk from? Did you build it yourself?

**Comment by ikopytko** [comment]
Yes, I'm building it. Tried a bunch of different forks before and this one is the closest to the working version, just made a couple mods. I'll join the discord

**Comment by mikeskydev** [comment]
Hey, thanks for the PR! We've decided to fix this by returning to the original published SDK version, 26. In the future we'll upgrade to the correct saving permissions instead of changing the manifest, see #23.

**Comment by mikeskydev** [comment]
After some thought, we'd like to move ahead with this following the discussion in #23. @ikopytko Please could you target the fix to `main` instead?

**Comment by ikopytko** [comment]
Yes, I'll create a new PR as there is no option to reopen existing one nor edit target  branch

**Pull request closed without merging**
