### PR TITLE
[Android] Enable building for ARM64/IL2CPP

### LINKED ISSUE #87: Building for Android IL2CPP fails
Oculus reccommend targeting arm64 for Quest builds, and suggest they might block arm7 in the future. I've previously tested this when submitting to app lab and some errors, which I think are coming from third party libraries.

### PR DESCRIPTION
**Pull request by mikeskydev**
Updates pngcs.dll which fixes an issue when building for ARM64/IL2CPP.

Fixes #87

Note https://github.com/icosa-gallery/open-brush/issues/87#issuecomment-819935956 as the possible regression with this PR.

The build pipeline has also been updated to target il2cpp as a future requirement for Oculus Quest builds.

### CODE REVIEW

**Comment by mikeage** [comment]
I'm not quite sure what happened with the CI jobs, and why we don't have logs from the Oculus failures. I'm going to rerun the jobs to see if that helps.

**Comment by mikeage** [comment]
Correction, I do know what happened:
```
Unhandled exception. System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
 ```

**Comment by mikeage** [comment]
Please review/merge #127 and then this should pass. I first tested #127 with a cherry-pick of these commits, and it built

**Comment by mikeage** [comment]
I'd like to give this a spin, so I synced it with `main`

**Review by mikeage — DISMISSED** [review]
The apk here crashes immediately after opening, before it even hits the circular fill loading screen. Perhaps something in the build cache? Not sure what else might be different from your local environment

**Comment by mikeskydev** [comment]
It does seem to be cache related, I deleted my Library folder on my local environment and it can now load and run the application. There may be an issue with saving and loading data which needs investigating, logs suggest it's from the JSON package.

**Comment by mikeage** [comment]
Ok -- can you please change the cache key so that the CI builds won't share the same Library directory as earlier ones, and then the CI images should hopefully work

**Comment by mikeage** [comment]
This is very strange... I just loaded the original APK (before the rebase, not that it matters), and it just loaded fine. I have no idea what changed :-/

**Comment by mikeskydev** [comment]
Okay, that's a weird one. We should probably dump cache anyways, how do I change the key in a way that doesn't break things going forward? I'll investigate the issue with the JSON package regardless.

**Comment by mikeage** [comment]
Just change the key (and the restore keys). Nothing will break, by definition, since it’s a cache, and we don’t really need it at all! But I’m not positive we need it... it seems like most of what’s in Library/ is related to importing assets and not to compilations.

does the apk here work for you? Maybe we can find some other people to try it?

I suspect it may have been related to the the v29 upgrade somehow... I had a few strange reboots afterwards, but since then my headset has been stable and this one is working.

**Comment by mikeage** [comment]
yep, can definitely confirm that loading and/or saving are broken, including the previews

**Comment by mikeage** [comment]
It looks like we need to replace Newtonsoft JSON with https://github.com/jilleJr/Newtonsoft.Json-for-Unity to get IL2CPP support. I don't know NuGet or Unity Packaging well enough to know what to do, exactly, though...

**Comment by mikeage** [comment]
When it says "newer" for the purpose of assembly validation, is this because of the 2019/2020 issue I mention on Discord? Were you able to test this on a SteamVR platform?

**Review by mikeage — APPROVED** [review]
Looks good on Q2!

**Comment by mikeskydev** [comment]
> When it says "newer" for the purpose of assembly validation, is this because of the 2019/2020 issue I mention on Discord? Were you able to test this on a SteamVR platform?

Sorry, more accurate to say that other plugins, specifically the Google API ones from the NuGet plugin, are hard locked to expect newtonsoft v10, whereas unity's version is v12 currently. On that note I did also explore the alternative of upgrading the Google plugins, but the NuGet plugin wasn't having any of it.

I'll give this a test on Steam later today! It did work through the editor using the SteamVR plugin though.

**Comment by mikeage** [comment]
Understood, thank you!

**Comment by mikeage** [comment]
> I'll give this a test on Steam later today! It did work through the editor using the SteamVR plugin though.

ping? :-)

**Comment by andybak** [comment]
I've got a suspicious this breaks building locally for Android (or at least the docs need updating). I need to do some proper testing but wanted to flag the hypothesis in case it's useful to others.

I had a situation where both ARM architecture checkboxes were unticked leading to a build error. Will try and reproduce.

**Pull request merged**
