### PR TITLE
Features/color jitter

### PR DESCRIPTION
**Pull request by andybak**
Jitter is accessed at the bottom of the color picker. A bit more info here: https://github.com/IxxyXR/open-brush/wiki/Color-Jitter

### CODE REVIEW

**Comment by mikeskydev** [comment]
Looks and works great! Only issue I can spot is a visual clash when accessing the jitter menu on certain color values: 
image

Can the attributions be changed to `Copyright 2021 The Open Brush Authors` in the relevant files as well please?

**Comment by andybak** [comment]
> Looks and works great! Only issue I can spot is a visual clash when accessing the jitter menu on certain color values:
> image

Ah yes. Do you think I can just bring the popup forward enough to not overlap or would that be too far forward?

> Can the attributions be changed to `Copyright 2021 The Open Brush Authors` in the relevant files as well please?

Yep

**Comment by mikeskydev** [comment]
> Ah yes. Do you think I can just bring the popup forward enough to not overlap or would that be too far forward?
I'd say so, it's not too much further! It's a minor thing to adjust/find another solution for later if it turns out to be an issue

**Review by mikeskydev — APPROVED** [review]
LGTM!

**Pull request merged**
