### PR TITLE
Revert "[Android] Enable building for ARM64/IL2CPP"

### PR DESCRIPTION
**Pull request by mikeskydev**
Reverts icosa-gallery/open-brush#126

Causes issues as logged in #209

### CODE REVIEW

**Comment by mikeage** [comment]
Does the newer newtonjson package work with the default build? Perhaps we can just revert the addition of `-btb-il2cpp` to fix the issue?

**Comment by mikeage** [comment]
I suspect the failures are not related, and is probably related to any new PR. I'll look at it shortly

**Comment by mikeage** [comment]
Please check #403, and maybe rebase on that once it's merged

**Comment by mikeskydev** [comment]
After testing, it looks like this fixes #209!

**Comment by mikeskydev** [comment]
> Does the newer newtonjson package work with the default build?

It probably would, but seemed to cause issues with the nuget packages we use. I'd like to take the opportunity to look at this problem more closely anyways

**Pull request merged**
