### PR TITLE
Snap improvements and Transform panel

### PR DESCRIPTION
**Pull request by andybak**
image

Transform Panel:

1. Lock/unlock x/y/z translations
2. Lock/unlock x/y/z rotations
3. Align selection in x/y/z to max/center/min

Snap Panel:

1. Enabled snapping independently on x/y/z axes
2. Snap selected widgets/strokes to grid
3. Snap selected widget rotation

Other changes:

1. Snap Position/rotation on import for models, images and video
2. Improved and new API commands related to the above.

Known issues/limitations:

1. Aligning video and images to max/min (center works fine) doesn't behave correctly on non-square images.
2. Groups are ignored in all bulk actions.
3. Brush strokes don't have an inherent concept of rotation so "snap to current snap angle" ignores brush strokes. I can think of a few ways to improve on this but it's out of scope for the initial version.

Testing matrix here: https://docs.google.com/spreadsheets/d/11biIkz5o1DzCc38peUAnNSNA24PtAoMuUxjycD5Czhs/edit?usp=sharing

### CODE REVIEW

**Comment by andybak** [comment]
Note that this commit also contains some WIP functionality that I decided to postpone just so I can get this out the door. I'd prefer to leave the WIP stuff in this commit as it's fiddly to separate and doesn't cause any harm or have side effects in it's current form:

1. Distribute min/center/max/spacing that complements the Align functionality
2. Align rotation of selected objects
3. Lock scale
4. Display of position/rotation/scale coordinates for selected objects
5. Simple numeric keyboard to type in and modify position/rotation/scale

**Comment by mikeage** [comment]
pre-commit fixed in https://github.com/icosa-gallery/open-brush/pull/307

**Comment by andybak** [comment]
We already have a button for "snap settings" that opens that panel.

Currently the transform panel doesn't have a button and is always present. I can _add_ a button but I do wonder if we'll end up with too many panel buttons (and too many panels).

Is this PR OK for now from a UX perspective or does it need more thought?

**Comment by andybak** [comment]
@merulaxr Added a button - decided to move both buttons to the "Extras" panel as Labs was full (and this isn't really Labs-ey)

**Comment by andybak** [comment]
Some known issues exist around different behaviours when selecting a widget vs grabbing a non-selected widget. (the origin is calculated differently).

I've noticed a few times I couldn't double click to deselect after using some features but haven't reliably reproduced it - and it seems to resolve itself quite swiftly

Regarding UI - yeah it could probably be more elegant. Mockups or detailed suggestions gratefully received!

**Pull request merged**
