### PR TITLE
Add uGIF encoder

### PR DESCRIPTION
**Pull request by ikopytko**
I have added export gif support using [simonwittber/uGIF](https://github.com/simonwittber/uGIF) library. I didn't enable the options for desktop, only for VR to avoid conflict in pending ffmpeg pull request. It can be enabled following the steps from readme.

### CODE REVIEW

**Comment by TimAidley** [comment]
I just tested this, and I found the following issues:

* Only 5-second gif was enabled, no auto-gif.
* No preview was displayed in the multicam when recording a gif.
* The 5-second gif has no watermark
* The auto-gif (once enabled) has a bar across the watermark.
image
Untitled_0_01
Untitled_0_00

**Comment by ikopytko** [comment]
- Instruction for some reason didn't include auto gif, but seems that there is no reason to not keep it on.
- Watermark is simply disabled in scene, need to enable it.
- The missing preview screen seems so far the worst bug, tried to track it down, but cannot say now why it doesn't work as the code to create preview is exactly the same as for picture taking. Atlas created based on camera for some reason is not working. I'll try to investigate it further. 
- Didn't check the black line yet.

**Comment by ikopytko** [comment]
Changes of second commit:
Watermark now enabled for 5-second
No black bar (was caused by black pixels on the edge of watermark, simply added 1px padding transparent from left and right)
Fixed preview for GIF
Enabled GIF options for PC and Mobile

**Review by mikeskydev — APPROVED** [review]
Thanks!

**Pull request merged**
