### PR TITLE
Add Open Brush startup logo

### PR DESCRIPTION
**Pull request by mikeskydev**
image
Update the logo to Open Brush! It's currently using a modified loading progress shader, which we can swap out for a properly drawn one later.

### CODE REVIEW

**Review by mikeage — APPROVED** [review]
looks great on a Q1 (Q2 battery is dead, but I can't imagine it'd be worse than a Q1!)

Much smoother than the initial loading logo, which is nice. The double spin, though (i.e, clockwise fill then counterclockwise undo), is different -- is that deliberate?

**Comment by mikeskydev** [comment]
Yep, the shader is hooked into `_IntroDissolve` which is what gives the brushes used in the intro the nice fade in/fade out effect

**Comment by mikeskydev** [comment]
image
Updated to make it fully transparent while it progresses, I think this is a bit better than having the translucent logo immediately there on startup?

**Comment by mikeskydev** [comment]
Tested on Q2 and Steam, seems to work well!

**Review by mikeage — APPROVED** [review]
looks great on Q1 too

**Pull request merged**
