### PR TITLE
Add Passthrough environment on Quest

### PR DESCRIPTION
**Pull request by merulaxr**
Enables passthrough mode on Quest and adds a new environment called 'Passthrough' to the environments panel 🚀

I still need to explore if we can add this capability on other platforms, would love to get Vive/Index working but I hear it's quite a hack. Passthrough is managed programmatically so should be quite easy to extend on other platforms as and when supported!

### CODE REVIEW

**Comment by merulaxr** [comment]
this branch also removes some of the android manifest settings that appear to be breaking other android-based headsets - will check once merged.

**Comment by andybak** [comment]
1. Is it me or do all the hull brushes look unlit?
2. Is there an easy way for the passthrough environment not to be last in the list? I feel it deserves more prominance!

**Comment by merulaxr** [comment]
Lights are added back, hopefully! Yes it should be simple enough to move the environment higher in the list, perhaps it could be first even if it loads to 'standard' by default?

**Comment by merulaxr** [comment]
Passthrough is first in the list, lights are re-enabled, and ambient has been set to a middle grey to give some shadow contrast

**Pull request merged**
