### PR TITLE
Use 90Hz if available on Oculus

### PR DESCRIPTION
**Pull request by mikeage**

### CODE REVIEW

**Comment by mikeage** [comment]
[not tested yet; waiting for the CI builds]

**Comment by mikeage** [comment]
works on Q2. My Q1 is currently unavailable

**Comment by merulaxr** [comment]
Andy's comment in #108 has got me thinking if default is the best idea again 😅 I really wish there was a platform agnostic way to display the options to users, but as we've found that's not available on all platforms as of yet.

**Comment by mikeage** [comment]
We can go back to the config file idea if we want.

Personally, I'm still concerned that we have no idea what our actual CPU (GPU?) budget looks like in the real world

**Pull request closed without merging**
