### PR TITLE
Enable Microsoft motion controller profile (WMR)

### LINKED ISSUE #376: No controllers - WMR
Hello first off - thank you for the ongoing development of this app.

As in the title - virtual controllers in Openbrush are not available with update 2.0 (SteamVR) version  (the app was working fine in version 1) .
I'm using a Samsung Oddessy+ HMD with the WMR controllers.
I have tried to use non-steamvr releases of Openbrush and ran into the same issue. 

What can I do to help diagnose this issue? 

---
SteamVR System Report created Thu Jan 26 12:19:23 2023

<Report>
SteamVR Version:	1.24.7 (1671750570)
SteamVR Date:	2022-12-22
Steam:	Steam Error
Steam Branch:	
Steam AppID:	250820
Tracking:	holographic
OS:	Windows 10
OS Version:	10.0.0.19044
Direct Mode Vendor:	NVIDIA
Direct Mode Version:	527.41
Admin:	No
AsyncReprojection:	Enabled
Performance drops:	1/1 0/2 0/3 0/4 2247/2248
Display Mode:	Direct Mode
</Report>

<Displays>
DeviceName:	\\.\DISPLAY2
DeviceDirectMode:	No
DevicePrimary:	Yes
DeviceRect:	1920x1080 @ (0, 0)
DeviceString:	NVIDIA GeForce RTX 2060
DeviceID:	PCI\VEN_10DE&DEV_1F08&SUBSYS_37D21458&REV_A1
DeviceMonitorCount:	1
Monitor 0 DeviceName:	\\.\DISPLAY2\Monitor0
Monitor 0 DeviceString:	Generic PnP Monitor
Monitor 0 DeviceID:	MONITOR\SAM0D20\{4d36e96e-e325-11ce-bfc1-08002be10318}\0011

DeviceName:	\\.\DISPLAY5
DeviceDirectMode:	No
DevicePrimary:	No
DeviceRect:	1920x1080 @ (0, -1080)
DeviceString:	Virtual Display Adapter
DeviceID:	VirtualDisplayAdapter_DisplayDevice_0000
DeviceMonitorCount:	1
Monitor 0 DeviceName:	\\.\DISPLAY5\Monitor0
Monitor 0 DeviceString:	Generic Non-PnP Monitor
Monitor 0 DeviceID:	MONITOR\Default_Monitor\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003

DeviceName:	\\.\DISPLAY6
DeviceDirectMode:	No
DevicePrimary:	No
DeviceRect:	1920x1080 @ (0, -2160)
DeviceString:	Virtual Display Adapter
DeviceID:	VirtualDisplayAdapter_DisplayDevice_0000
DeviceMonitorCount:	1
Monitor 0 DeviceName:	\\.\DISPLAY6\Monitor0
Monitor 0 DeviceString:	Generic Non-PnP Monitor
Monitor 0 DeviceID:	MONITOR\Default_Monitor\{4d36e96e-e325-11ce-bfc1-08002be10318}\0004

DeviceName:	\\.\DISPLAY7
DeviceDirectMode:	No
DevicePrimary:	No
DeviceRect:	1920x1080 @ (0, -3240)
DeviceString:	Virtual Display Adapter
DeviceID:	VirtualDisplayAdapter_DisplayDevice_0000
DeviceMonitorCount:	1
Monitor 0 DeviceName:	\\.\DISPLAY7\Monitor0
Monitor 0 DeviceString:	Generic Non-PnP Monitor
Monitor 0 DeviceID:	MONITOR\Default_Monitor\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005

</Displays>

<Devices>
Device 1 - WindowsHolographic Headset Samsung Windows Mixed Reality 800ZBA0 WindowsMR
Device Path:	/devices/holographic/WindowsHolographic
Best Alias:	/user/head
Firmware: 	
Hardware Revision: 	
Camera Firmware: 	Version not available.
VSync to Photons: 	0.02
Display Frequency:	59.999
User IPD (m):	0.0601121
Current Universe ID:	7001611838800
Previous Universe ID:	0

Device 2 - MRSOURCE0 Controller WindowsMR: 0x045E/0x065D/0/1 WindowsMR: 0x045E
Device Path:	/devices/holographic/MRSOURCE0
Best Alias:	/user/hand/left
Firmware: 	
Hardware Revision: 	
Attached Device ID: 	
Supported Buttons:	0
Axis 0 Type:	1
Axis 1 Type:	3
Axis 2 Type:	2
Axis 3 Type:	0
Axis 4 Type:	0
Connected Dongle:	 Version: Unknown Version

Device 3 - MRSOURCE1 Controller WindowsMR: 0x045E/0x065D/0/2 WindowsMR: 0x045E
Device Path:	/devices/holographic/MRSOURCE1
Best Alias:	/user/hand/right
Firmware: 	
Hardware Revision: 	
Attached Device ID: 	
Supported Buttons:	0
Axis 0 Type:	1
Axis 1 Type:	3
Axis 2 Type:	2
Axis 3 Type:	0
Axis 4 Type:	0
Connected Dongle:	 Version: Unknown Version

</Devices>

### PR DESCRIPTION
**Pull request by mikeskydev**
Fixes #376 
Controller rotation may be off, requesting some tests!

### CODE REVIEW

**Comment by mikeskydev** [comment]
@liuprestin @n1ckfg would it be possible for you to test these builds when they're done? It's not perfect but it's a lot better! https://nightly.link/icosa-gallery/open-brush/workflows/build/fix%2Fwmr
still a slight bounce issue when on the brush list, the thumbstick deadzone seems to work differently there.

**Comment by liuprestin** [comment]
No problem,

I'll hop on and test no later than tomorrow (feb 10th)

**Comment by liuprestin** [comment]
Update: Just tested - the profile - the menus on the left hand rotate as expected 

I noticed that the rumble response is stronger for all interactions on both controllers as if the motors are on full blast.  
It maybe abit too strong since the rumble on wmr controllers can give a light and sensitive feedback response.  
I'm also worried that it may wear down the battery. (Is there a setting that turns rumble off now that I'm mentioning this) 

Was there another interaction you wanted to test? @mikeskydev

**Comment by mikeskydev** [comment]
Thanks, that's great! I now remember I was able to adjust rumble strength for some other controllers, the default OpenXR rumble was very high. I'll tune it tomorrow and get this merged in, thanks again for your help!

**Pull request merged**
