### PR TITLE
Automatically generate changelog, rather than doing it manually

### PR DESCRIPTION
**Pull request by mikeage**

### CODE REVIEW

**Comment by mikeage** [comment]
Tested on my fork, but there's a (small, hopefully) chance that there might be an issue on this repo. It should be no worse than what we have now, though!

**Comment by mikeskydev** [comment]
This looks interesting! should commits follow a certain naming structure (like apache) to properly group by category?

**Comment by mikeage** [comment]
> This looks interesting! should commits follow a certain naming structure (like apache) to properly group by category?

Yes... and no ;-)

1. Commits don't matter. This actually looks at the PRs only (won't matter for us since we never merge to `main` without a PR)
2. It uses the labels. If they're tagged, it'll go in that section. If not, there's a miscellaneous section at the end ("uncategorized")

**Review by mikeskydev — APPROVED** [review]

**Comment by mikeage** [comment]
Cool, that actually works! (although it shouldn't show the Uncategorized category if there are none)

**Pull request merged**
