### PR TITLE
Add FBX SDK

### PR DESCRIPTION
**Pull request by mikeskydev**
Adds the compiled FBX package that results from following the steps in https://github.com/icosa-gallery/open-brush/blob/main/Support/fbx/README.md

I haven't tested this on my Quest specific fork so there may be CI issues to solve.

### CODE REVIEW

**Comment by mikeskydev** [comment]
@mikeage I'm guessing we need to add another exclusion filter to precommit for the packages folder?

**Comment by mikeage** [comment]
I actually like the changes it made… but I don’t think we should be touching 3rd party code unless it’s an actual bug fix, so yes

**Comment by mikeage** [comment]
Github is being a bit wonky when showing me the diff (because it's huge) -- in projectsettings, can you remind me what the 14 is for?

```
   scriptingDefineSymbols:
    1: USD_SUPPORTED;UNITY_HAS_GOOGLEVR;TILT_BRUSH;FBX_SUPPORTED;FBXSDK_RUNTIME
     7: TILT_BRUSH;OCULUS_SUPPORTED
     14: USD_SUPPORTED;UNITY_HAS_GOOGLEVR;TILT_BRUSH
```

I know 7 is Quest -- I think 1 covers both SteamVR and Rift native, right?

**Review by andybak — APPROVED** [review]
Can't think of much I'd be able to see from the PR. The proof of the puddling will be in the build so I think we should merge. Do we need to exclude the autodesk stuff from the code format checks?

**Comment by mikeskydev** [comment]
> Do we need to exclude the autodesk stuff from the code format checks?

Yeah we do, I was having a look at how to exclude multiple folders from pre-commit but can't quite work out the regex!

**Comment by mikeage** [comment]
I'll take care of the pre-commit stuff now

**Comment by mikeage** [comment]
Done. @mikeskydev  / @andybak , is there any more testing that needs to be done?

**Comment by andybak** [comment]
I suppose this might potentially break exports in builds. I've tested in Unity. 

I've slightly lost track of the state of affairs without this PR. The decider should probably be "What's the worst that can happen?" vs "How broken is it before this?"

**Comment by andybak** [comment]
By my recollection - fbx support worked in official builds before but not in the editor. Is that right? And it wasn't enabled in PR builds. It will still fail in experimental builds because of the new brushes (I've got a branch that fixes this crudely - at least to the point where the exports work but new brush strokes look weird).

**Comment by mikeskydev** [comment]
Yeah, on official builds I just built it from my own computer to add FBX.

Sidenote, I'll update the README to remove the references to adding FBX support!

**Pull request merged**
