### PR TITLE
Features/point cloud import

### PR DESCRIPTION
**Pull request by andybak**
I guess the big question is whether to enable this for the Quest. It works but it's pretty easy to slow things down to a crawl with big point clouds. It seemed bearable on a Quest 2 when I imported a model with 238,000 points and created 2 or 3 copies of it. (My 3080 PC was pretty happy with about 20 or more copies!).

I guess it's still useful. One small addition that might help would be a "skip every n points" option in the config. Or maybe an automatic setting that did this based on the number of points? Getting good defaults would be tricky though as everyone's use case would be different.

All in all - this is niche enough that I'd probably advocate releasing as is to get feedback. It's a nice addition to the supported reference models especially as lots of people can scan point clouds on their iPhones now.

### CODE REVIEW

**Comment by andybak** [comment]
Question - I've used and modified bits of https://github.com/keijiro/Pcx but there not put them in separate folders. Where's the right place to give credit and copyright? At the top of each file that uses Keijiro's work?

**Comment by merulaxr** [comment]
Will review this soon, can I have a sample file to import? :D

> I've used and modified bits of https://github.com/keijiro/Pcx

Is it possible to use the scoped registry for the bulk of the code, and keep your modifications separately somehow? Would be good to thin the codebase of things that aren't strictly necessary

**Comment by andybak** [comment]
> Is it possible to use the scoped registry for the bulk of the code, and keep your modifications separately somehow? Would be good to thin the codebase of things that aren't strictly necessary

Hmmm. I moved a chunk of code from Editor to Runtime and removed stuff we don't need. I could fork Pcx and create my own OpenUPM entry I guess?

But is it worth it? There's basically only 1 C# script, 1 material and a few shaders files and we'd still need a stub of the C#

**Comment by andybak** [comment]
Test files:

https://github.com/keijiro/Pcx/blob/master/Assets/nebulousflynn/anthidium-forcipatum.ply

https://github.com/keijiro/Pcx/blob/master/Assets/GeoffreyMarchal/Guanyin.ply

**Review by merulaxr — APPROVED** [review]
LGTM! Nice feature to have :)

**Pull request merged**
