### PR TITLE
Change SketchFab uploads to upload as Open Brush

### PR DESCRIPTION
**Pull request by PerlinWarp**
It looks like you're sending `source: "tilt-brush"` and tags `tags: ["tiltbrush"]` in the upload POST. If you change those to `open-brush` or `openbrush`, I'll take care of the rest on my end. Just let me know which you choose for each. - James Green, SketchFab

Let me do some more testing before merging.

### CODE REVIEW

**Comment by mikeskydev** [comment]
I can see both tags, but not the source. Do Sketchfab need to approve the source name from their side? I also tried changing the source name to `Open Brush` as per our original application for API keys, but that didn't show either

**Comment by mikeskydev** [comment]
@PerlinWarp based on our conversation we're just waiting on Sketchfab here, is this good to commit anyways?

**Comment by PerlinWarp** [comment]
@mikeskydev I am yet to test this actually works, after writing it I needed secrets then got sidetracked by the Quest crashing bug. Sketchfab says it should work using a custom source but I wanted an example Sketchfab upload to post before merging. Apologies for the delay!

**Comment by mikeage** [comment]
We don't do secrets in PR builds from forks (because they rely on secrets and forks are not guaranteed to be safe from credential leakage), but after #71 is merged, if you want to open a PR from a branch of this repo rather than a fork (and I believe you have write permissions), you can get the sketchfab secrets built in to your CI build!

**Comment by PerlinWarp** [comment]
Rebased and retested. 
Here are two examples: (Don't judge my lack of artistry 😉)

[PCVR Upload Test](https://sketchfab.com/3d-models/d07f0616f05b4870a0aa37db59801423)
[Oculus Quest 1 Upload Test](https://sketchfab.com/3d-models/d07f0616f05b4870a0aa37db59801423)

I can now send these to SketchFab to use as examples of what uploads from Open Brush will look like and what the source tag will be. So after merging this PR, the source tag will be  "open-brush" and new uploads will be given tags: "openbrush" and "tiltbrush".  Before I sent these to SketchFab, can I confirm we want to use these tags?

**Review by mikeskydev — APPROVED** [review]
LGTM!

**Pull request merged**
