### PR TITLE
Features/moatmerge

### PR DESCRIPTION
**Pull request by andybak**
@moatdd 's  features as documented here: 

https://www.youtube.com/watch?v=_d34eBiTtGA
https://www.youtube.com/watch?v=2CEyUrv3IZk
https://www.youtube.com/watch?v=ufGpqmul4Rc
https://www.youtube.com/watch?v=Wtx5uAF0GXs
https://www.youtube.com/watch?v=qJf4Wsu_EJA

### CODE REVIEW

**Comment by mikeage** [comment]
@andybak , that branch was not one that I actually used in the end. Ummm. Sorry.

**Comment by mikeskydev** [comment]
As discussed on Discord, what's the best approach for the last feature on this list (TOD)? It's activation gesture is quite obscure, so it could happily sit unused until we decide what's best for it. The same applies to the extra snap feature that is part of the TOD as well.

**Comment by andybak** [comment]
Moat's snapping is actually disabled in this merge (because my snapping conflicted with it in terms of code changes)

I think we should disable the display side of TOD as well as it has a grid that doesn't match the snapping grid (and as you say the activation gesture is a bit obscure).

It's easier to leave the code in but if we decide we aren't ever going to activate the TOD I can have a cleanup.

**Comment by andybak** [comment]
Addendum: This branch is the combined PR198 plus Moat: https://github.com/IxxyXR/open-brush/tree/features/moatmerge-plusPR198

I haven't made it a PR yet. Shall I? If so it will supercede this branch and PR198 (we can rename to make it clearer)

**Comment by mikeskydev** [comment]
If that's going to be the cleaner way to get all these in right now, that's probably a good idea!

**Comment by mikeskydev** [comment]
Merged via #200

**Pull request closed without merging**
