### PR TITLE
Changes for 0.3.0 release

### PR DESCRIPTION
**Pull request by mikeskydev**
Tidy up readme, update version numbers

### CODE REVIEW

**Review by mikeage — APPROVED** [review]
Looks great! When you merge this, you'll get a 0.2.30 build on `main`, but after you push the `v0.3` tag to main (on the squashed merge commit), it'll build `0.3.0` and create the release in github. (hopefully ;-) )

**Comment by mikeskydev** [comment]
Thanks for checking, and reminding me which tag I need to make! Will add the GitHub sponsors link and squash.

**Comment by mikeskydev** [comment]
@mikeage so close! Looks like it didn't pull the full changelog since 0.2?

**Comment by mikeage** [comment]
Hmmm... did you update the changelog? What's there now looks perfect... I can check the logs from the action

**Comment by mikeskydev** [comment]
Yes, I've brought in from all the other changelogs manually, it just had the single most recent change before

**Comment by mikeage** [comment]
Gotcha. It looks like this test wasn't correct:
```bash
if [ $(git describe --tags --abbrev=0) == $(git describe --tags) ]
then
    PREV=$(git describe --tags --abbrev=0 HEAD^)
else
    PREV=$(git describe --tags --abbrev=0)
fi
```  
I'll check why in a little bit (going home now). Sorry about that!

**Comment by mikeage** [comment]
Oh, duh, of course. I copy pasted the wrong thing when I finally merge this. Will fix soon.

**Comment by mikeage** [comment]
Fixed in https://github.com/icosa-gallery/open-brush/pull/101 (along with a bit of duplicate code removed)

**Pull request merged**
