### PR TITLE
Add websocket support to the API server

### PR DESCRIPTION
**Pull request by andybak**
Adds basic websocket support to the API server. Listens on port 40075

### CODE REVIEW

**Comment by andybak** [comment]
Making this draft until I test support for allowing only local connections

**Comment by andybak** [comment]
Just tested and can confirm EnableApiRemoteCalls works as expected with websockets. Also fixed a bug where it would only accept local connections no matter what setting you used.

**Review by mikeage — APPROVED** [review]
Looks sensible to me. I didn't review every single line, but I'm happy with this

**Review by mikeskydev — COMMENTED** [review]
Nit: Can the changes be added to the HttpServer prefab instead of main? otherwise, LGTM!

**Comment by andybak** [comment]
> Nit: Can the changes be added to the HttpServer prefab instead of main? otherwise, LGTM!

Done

**Review by mikeskydev — APPROVED** [review]

**Pull request merged**
